version: "3"
services:
  mongo:
    restart: on-failure
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      # - ${MONGO_HOST_DATA}/.database:/data/db
    ports:
      - "27017:27017"
